"""empty message

Revision ID: 2864933ec476
Revises: 
Create Date: 2020-05-01 15:50:39.744227

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2864933ec476'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))

    # update existing record with SQL update statement 
    op.execute('UPDATE todos SET completed = False Where completed is Null;') 
    
    # update column, Completed column nullable = False 
    op.alter_column('todos', 'completed', nullable=False)

    # ### end Alembic commands ###



def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
